charts/activemq-artemis/Chart.yaml
charts/activemq-artemis/templates/_helpers.tpl
charts/activemq-artemis/templates/rbac.yaml
charts/activemq-artemis/templates/serviceaccounts.yaml
charts/activemq-artemis/templates/statefulsets.yaml
charts/gxf/Chart.yaml

FDP-502: Let user override ActiveMQ service account name

---

charts/gxf/Chart.yaml

FDP-502: Use new ActiveMQ chart

---

charts/activemq-artemis/Chart.yaml
charts/activemq-artemis/templates/serviceaccounts.yaml

Don't create ServiceAccount when the name is set to 'default'

---

charts/activemq-artemis/Chart.yaml
charts/activemq-artemis/templates/statefulsets.yaml

FDP-502: Liveness probe initial delay increased

---

charts/gxf/Chart.yaml
charts/gxf/templates/deployment.yaml

FDP-591: Alignment corrected

---

charts/gxf/Chart.yaml
charts/gxf/values.yaml

FDP-502: ActiveMQ memory increased

---

charts/gxf/Chart.yaml
charts/gxf/values.yaml

FDP-527: resources used from artemis chart

---

charts/gxf/Chart.yaml
charts/gxf/templates/service.yaml

FDP-604: Reverted: Enable overriding targetPort

---

charts/gxf/Chart.yaml
charts/gxf/templates/apache-config.yaml

FDP-426: move httpd files to world-writeable location

---

charts/gxf/Chart.yaml
charts/gxf/templates/deployment.yaml

FDP-426: httpd password was not executable

---

charts/gxf/Chart.yaml
charts/gxf/templates/deployment.yaml

Signed-off-by: Marcel Jansen <34770714+Marcel-Jansen@users.noreply.github.com>

quote env values

---

charts/gxf/Chart.yaml
charts/gxf/templates/apache-config.yaml
charts/gxf/templates/efs-storage.yaml
charts/gxf/templates/ingress.yaml

Signed-off-by: Loes Immens <loes.immens@alliander.com>

FDP-759: recommitted changes on new branch now signed off

---

charts/gxf/Chart.yaml
charts/gxf/templates/ingress.yaml

Signed-off-by: Marcel Jansen <34770714+Marcel-Jansen@users.noreply.github.com>

Update Ingress API to v1

---

charts/gxf/Chart.yaml
charts/gxf/templates/ingress.yaml

Signed-off-by: Marcel Jansen <34770714+Marcel-Jansen@users.noreply.github.com>

Add required pathType to Ingress

---

charts/gxf/Chart.yaml
charts/gxf/templates/ingress.yaml

Makes sure both ingressgate and ingress use the same path structure

Syncs ingressgate with ingress

---

charts/gxf/Chart.yaml

Signed-off-by: Sander <sander@verbruggen.ws>

FDP-892: Version bump for gxf to include latest ActiveMQ chart

---

charts/gxf/Chart.yaml
charts/gxf/templates/efs-storage.yaml

FDP-584: make storage class configurable

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
charts/activemq-artemis/Chart.yaml
charts/activemq-artemis/templates/configmaps.yaml
charts/activemq-artemis/templates/statefulsets.yaml
charts/activemq-artemis/values.yaml

Add no ssl option

---

charts/gxf/Chart.yaml
charts/gxf/templates/deployment.yaml

Signed-off-by: Sander <sander.verbruggen@alliander.com>

FDP-957: Added optional default health probes

---

charts/gxf/Chart.yaml
charts/gxf/templates/deployment.yaml

Add if statement around probes

---

charts/gxf/Chart.yaml
charts/gxf/values.yaml

Correct httpd image

---

charts/activemq-artemis/Chart.yaml
charts/activemq-artemis/values.yaml

Quote properties to avoid type mapping

---

charts/gxf/Chart.yaml
charts/gxf/templates/deployment.yaml
charts/gxf/values.yaml

Revert default probes

---

charts/gxf/Chart.yaml
charts/gxf/templates/ingress-gate.yaml
charts/gxf/templates/ingress.yaml
charts/gxf/templates/route.yaml
charts/gxf/templates/service.yaml
charts/gxf/values.yaml

FDP-1037: Use fixed service ports

---

charts/activemq-artemis/Chart.yaml
charts/activemq-artemis/templates/statefulsets.yaml
charts/gxf/Chart.yaml
charts/gxf/templates/deployment.yaml

FDP-1116: Correct image pull secret

---

charts/gxf/Chart.yaml
charts/gxf/templates/deployment.yaml

Use probe endpoint for the liveness check and the metrics endpoint for the readiness check.

FDP-1303: Update deployment probes

---

README.md
charts/gxf/Chart.yaml
charts/gxf/templates/deployment.yaml
charts/gxf/templates/prometheus-probe-script.yaml

FDP-1566: Probe script scanning all configured Prometheus endpoints

---

charts/gxf/Chart.yaml
charts/gxf/config/tomcat/server.xml
charts/gxf/templates/deployment.yaml

Make clientAuth parameterizable and optional.

Improved https connector config

---

charts/gxf/Chart.yaml
charts/gxf/templates/certificate-keystore-secret.yaml
charts/gxf/values.yaml

fix lint and rename parameter sealedSecretsManaged to managedBySealedSecret

fix lint and parameter name
